version: '3'
services:

  config:
    container_name: config
    image: jeffersonbraga/config:1.0
    restart: always
    environment:
      URI: 'https://github.com/jeffersonbraga/microservices-jeff.git'
    ports:
      - 8888:8888
    expose:
      - 8888

  discovery:
    container_name: discovery
    image: jeffersonbraga/discovery:1.0
    restart: always
    environment:
      CONFIG_SERVER_URL: 'http://config:8888'
    ports:
      - 8761:8761
    expose:
      - 8761
    depends_on:
      - config

  tickers:
    container_name: tickers
    image: jeffersonbraga/tickers:1.0
    restart: always
    environment:
      CONFIG_SERVER_URL: 'http://config:8888'
    ports:
      - 8085:8085
    expose:
      - 8085
    depends_on:
      - config
